/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LocalRouteImport } from './routes/local'
import { Route as OnlineRouteImport } from './routes/online'
import { Route as PartiesRouteImport } from './routes/parties'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PuzzlesRouteImport } from './routes/puzzles'
import { Route as ApiPublicHooksDebugOnlineRouteImport } from './routes/api/public/hooks/debug-online'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalRoute = LocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineRoute = OnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesRoute = PartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesRoute = PuzzlesRouteImport.update({
  id: '/puzzles',
  path: '/puzzles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDebugOnlineRoute =
  ApiPublicHooksDebugOnlineRouteImport.update({
    id: '/api/public/hooks/debug-online',
    path: '/api/public/hooks/debug-online',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/auth': typeof AuthRoute
  '/local': typeof LocalRoute
  '/online': typeof OnlineRoute
  '/parties': typeof PartiesRoute
  '/profile': typeof ProfileRoute
  '/puzzles': typeof PuzzlesRoute
  '/api/public/hooks/debug-online': typeof ApiPublicHooksDebugOnlineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/auth': typeof AuthRoute
  '/local': typeof LocalRoute
  '/online': typeof OnlineRoute
  '/parties': typeof PartiesRoute
  '/profile': typeof ProfileRoute
  '/puzzles': typeof PuzzlesRoute
  '/api/public/hooks/debug-online': typeof ApiPublicHooksDebugOnlineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/auth': typeof AuthRoute
  '/local': typeof LocalRoute
  '/online': typeof OnlineRoute
  '/parties': typeof PartiesRoute
  '/profile': typeof ProfileRoute
  '/puzzles': typeof PuzzlesRoute
  '/api/public/hooks/debug-online': typeof ApiPublicHooksDebugOnlineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arena'
    | '/auth'
    | '/local'
    | '/online'
    | '/parties'
    | '/profile'
    | '/puzzles'
    | '/api/public/hooks/debug-online'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arena'
    | '/auth'
    | '/local'
    | '/online'
    | '/parties'
    | '/profile'
    | '/puzzles'
    | '/api/public/hooks/debug-online'
  id:
    | '__root__'
    | '/'
    | '/arena'
    | '/auth'
    | '/local'
    | '/online'
    | '/parties'
    | '/profile'
    | '/puzzles'
    | '/api/public/hooks/debug-online'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArenaRoute: typeof ArenaRoute
  AuthRoute: typeof AuthRoute
  LocalRoute: typeof LocalRoute
  OnlineRoute: typeof OnlineRoute
  PartiesRoute: typeof PartiesRoute
  ProfileRoute: typeof ProfileRoute
  PuzzlesRoute: typeof PuzzlesRoute
  ApiPublicHooksDebugOnlineRoute: typeof ApiPublicHooksDebugOnlineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local': {
      id: '/local'
      path: '/local'
      fullPath: '/local'
      preLoaderRoute: typeof LocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online': {
      id: '/online'
      path: '/online'
      fullPath: '/online'
      preLoaderRoute: typeof OnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties': {
      id: '/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof PartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles': {
      id: '/puzzles'
      path: '/puzzles'
      fullPath: '/puzzles'
      preLoaderRoute: typeof PuzzlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/debug-online': {
      id: '/api/public/hooks/debug-online'
      path: '/api/public/hooks/debug-online'
      fullPath: '/api/public/hooks/debug-online'
      preLoaderRoute: typeof ApiPublicHooksDebugOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArenaRoute: ArenaRoute,
  AuthRoute: AuthRoute,
  LocalRoute: LocalRoute,
  OnlineRoute: OnlineRoute,
  PartiesRoute: PartiesRoute,
  ProfileRoute: ProfileRoute,
  PuzzlesRoute: PuzzlesRoute,
  ApiPublicHooksDebugOnlineRoute: ApiPublicHooksDebugOnlineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
